const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$('#menu').addEventListener('click',()=>$('#nav').classList.toggle('open')); $$('#nav a').forEach(a=>a.addEventListener('click',()=>$('#nav').classList.remove('open')));
const techs=['Bordado','DTF','Serigrafía','Sublimación','Vinil']; let complex=false;
function renderTech(){const material=$('#garment').value; const box=$('#techs'); box.innerHTML=''; let notes=[]; techs.forEach((t,i)=>{let ok=true,msg=''; if(complex&&t==='Vinil'){ok=false;msg='demasiado detalle/degradados para corte de vinil'} if(complex&&t==='Bordado'){ok=false;msg='requiere revisión por complejidad'} if(t==='Sublimación'&&material!=='Camiseta'){ok=false;msg='confirmar composición/material antes de sublimar'} const d=document.createElement('label'); d.className='tech'+(ok?'':' disabled'); d.innerHTML=`<span>${t}</span><input type="radio" name="tech" value="${t}" ${ok?'':'disabled'} ${i===1?'checked':''}>`; box.appendChild(d); if(!ok) notes.push(`${t}: ${msg}.`)}); $('#reason').textContent=notes.join(' '); calc()}
function calc(){let q=$$('.qty').reduce((a,x)=>a+(+x.value||0),0); $('#totalQty').textContent=q; let tech=$('input[name=tech]:checked')?.value||'DTF'; let base={Bordado:420,DTF:350,Serigrafía:320,Sublimación:360,Vinil:330}[tech]; let disc=q>=24?.82:q>=12?.9:1; $('#price').textContent=`C$ ${Math.round(base*Math.max(q,1)*disc).toLocaleString()}`}
$$('.qty').forEach(x=>x.addEventListener('input',calc)); $('#garment').addEventListener('change',renderTech); $('#techs').addEventListener('change',calc);
$('#audience').addEventListener('change',e=>{const map={Hombre:'Corte hombre',Mujer:'Corte mujer',Niño:'Corte infantil niño',Niña:'Corte infantil niña'}; $('#viewNote').textContent=map[e.target.value]+' • el modelo 3D final debe corresponder a la prenda real.'});
$('#color').addEventListener('input',e=>{const c=e.target.value;$('#model').style.background=`linear-gradient(90deg,color-mix(in srgb, ${c} 78%, #555),${c} 22%,color-mix(in srgb, ${c} 96%, white) 50%,${c} 78%,color-mix(in srgb, ${c} 78%, #555))`});
$('#file').addEventListener('change',e=>{const f=e.target.files[0]; if(!f)return; complex=f.size>300000; const mark=$('#designMark'); const r=new FileReader(); r.onload=()=>{mark.textContent='';mark.style.background=`url(${r.result}) center/contain no-repeat`;mark.style.width='145px';mark.style.height='145px';mark.style.border='0'};r.readAsDataURL(f);renderTech()});
$$('.tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#designMark').textContent=b.dataset.view==='front'?'TU DISEÑO':b.textContent.toUpperCase()}));
$('#view3d').addEventListener('click',()=>{$('#model').classList.add('spin');$('#view3d').classList.add('active');$('#view2d').classList.remove('active');$('#viewNote').textContent='Demostración 360°. Sustituye este modelo CSS por modelos 3D reales de tus prendas.'}); $('#view2d').addEventListener('click',()=>{$('#model').classList.remove('spin');$('#view2d').classList.add('active');$('#view3d').classList.remove('active')});
let cart=0; $$('.cart').forEach(b=>b.addEventListener('click',()=>{$('#cartStatus').textContent=`Producto agregado. Carrito: ${++cart} artículo(s).`})); $('#add').addEventListener('click',()=>{$('#cartStatus').textContent='Configuración personalizada agregada al pedido.'; location.hash='tienda'});
$$('.video').forEach(b=>b.addEventListener('click',()=>{$('#videoTitle').textContent=b.dataset.title;$('#videoModal').showModal()})); $('#closeModal').addEventListener('click',()=>$('#videoModal').close()); renderTech();