const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
$('#menu')?.addEventListener('click',()=>$('#nav')?.classList.toggle('open')); $$('#nav a').forEach(a=>a.addEventListener('click',()=>$('#nav')?.classList.remove('open')));
const techs=['Bordado','DTF','Serigrafía','Sublimación','Vinil']; let complex=false;
function renderTech(){if(!$('#techs'))return; const material=$('#garment').value,box=$('#techs');box.innerHTML='';let notes=[];techs.forEach((t,i)=>{let ok=true,msg='';if(complex&&t==='Vinil'){ok=false;msg='demasiado detalle/degradados para corte de vinil'}if(complex&&t==='Bordado'){ok=false;msg='requiere revisión por complejidad'}if(t==='Sublimación'&&material!=='Camiseta'){ok=false;msg='confirmar composición/material antes de sublimar'}const d=document.createElement('label');d.className='tech'+(ok?'':' disabled');d.innerHTML=`<span>${t}</span><input type="radio" name="tech" value="${t}" ${ok?'':'disabled'} ${i===1?'checked':''}>`;box.appendChild(d);if(!ok)notes.push(`${t}: ${msg}.`)});$('#reason').textContent=notes.join(' ');calc()}
function calc(){if(!$('#price'))return;let q=$$('.qty').reduce((a,x)=>a+(+x.value||0),0);$('#totalQty').textContent=q;let tech=$('input[name=tech]:checked')?.value||'DTF',base={Bordado:420,DTF:350,Serigrafía:320,Sublimación:360,Vinil:330}[tech],disc=q>=24?.82:q>=12?.9:1;$('#price').textContent=`C$ ${Math.round(base*Math.max(q,1)*disc).toLocaleString()}`}
$$('.qty').forEach(x=>x.addEventListener('input',calc));$('#garment')?.addEventListener('change',renderTech);$('#techs')?.addEventListener('change',calc);
$('#audience')?.addEventListener('change',e=>{const map={Hombre:'Corte hombre',Mujer:'Corte mujer',Niño:'Corte infantil niño',Niña:'Corte infantil niña'};$('#viewNote').textContent=map[e.target.value]+' • arrastra la prenda para verla desde distintos ángulos.'});
$('#color')?.addEventListener('input',e=>{const c=e.target.value;$('#model').style.background=`linear-gradient(90deg,color-mix(in srgb, ${c} 72%, #555),${c} 20%,color-mix(in srgb, ${c} 96%, white) 50%,${c} 80%,color-mix(in srgb, ${c} 72%, #555))`});
$('#file')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;complex=f.size>300000;const mark=$('#designMark'),r=new FileReader();r.onload=()=>{mark.textContent='';mark.style.background=`url(${r.result}) center/contain no-repeat`;mark.style.width='145px';mark.style.height='145px';mark.style.border='0'};r.readAsDataURL(f);renderTech()});
$$('.tabs button').forEach(b=>b.addEventListener('click',()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const angles={front:0,back:180,left:-75,right:75};rotY=angles[b.dataset.view]||0;applyRotation()}));
let rotY=0,rotX=0,drag=false,lastX=0,lastY=0;function applyRotation(){if($('#model'))$('#model').style.transform=`rotateX(${rotX}deg) rotateY(${rotY}deg)`}const studio=$('#dragStudio');if(studio){const start=(x,y)=>{drag=true;lastX=x;lastY=y},move=(x,y)=>{if(!drag)return;rotY+=(x-lastX)*.65;rotX=Math.max(-18,Math.min(18,rotX-(y-lastY)*.18));lastX=x;lastY=y;applyRotation()},end=()=>drag=false;studio.addEventListener('pointerdown',e=>{studio.setPointerCapture(e.pointerId);start(e.clientX,e.clientY)});studio.addEventListener('pointermove',e=>move(e.clientX,e.clientY));studio.addEventListener('pointerup',end);studio.addEventListener('pointercancel',end)}
let cart=0;$$('.cart').forEach(b=>b.addEventListener('click',()=>{if($('#cartStatus'))$('#cartStatus').textContent=`Producto agregado. Carrito: ${++cart} artículo(s).`}));$('#add')?.addEventListener('click',()=>alert('Configuración agregada al pedido.'));
$$('.video').forEach(b=>b.addEventListener('click',()=>{if($('#videoTitle'))$('#videoTitle').textContent=b.dataset.title;$('#videoModal')?.showModal()}));$('#closeModal')?.addEventListener('click',()=>$('#videoModal')?.close());renderTech();
